.Dd dsfs
.Dt MDOC_OS_TEST 5
.Os
.Sh NAME
.Nm mdoc_ostest
.Nd check rendering of the Operating Systems macros
.Sh DESCRIPTION
.At
.Pp
.At v6
.Pp
.At 32v
.Pp
.At III
.Pp
.At V
.Pp
.At V.4
.Pp
.Bsx
.Pp
.Bsx 1.0
.Pp
.Bx
.Pp
.Bx -alpha
.Pp
.Bx -beta
.Pp
.Bx -devel
.Pp
.Bx 2
.Pp
.Bx -beta 2
.Pp
.Bx 4.2
.Pp
.Bx Tahoe
.Pp
.Bx tahoe
.Pp
.Bx 4.3	Tahoe
.Pp
.Bx 4.3	tahoe
.Pp
.Bx Reno
.Pp
.Bx reno
.Pp
.Bx 4.3	Reno
.Pp
.Bx 4.3	reno
.Pp
.Bx Lite
.Pp
.Bx lite
.Pp
.Bx 4.4 Lite
.Pp
.Bx 4.4 lite
.Pp
.Bx Lite2
.Pp
.Bx lite2
.Pp
.Bx 4.4 Lite2
.Pp
.Bx 4.4 lite2
.Pp
.Dx
.Pp
.Dx 2.4.1
.Pp
.Fx
.Pp
.Fx 7.1
.Pp
.Fx 13.0-RELEASE-p3
.Pp
.Nx
.Pp
.Nx 5.01
.Pp
.Ox
.Pp
.Ox 4.5
.Pp
.Ux
